loglevel: 4

log_rotate_size: 10485760
log_rotate_date: ""
log_rotate_count: 1

log_rate_limit: 100

certfiles:
  - "{{ settings.CERTS_DIR }}/*.pem"
{% for dir in settings.XMPP_SERVER_ADD_CERTS_DIRS %}
  - "{{ dir }}/*.pem"
{% endfor %}
ca_file: "{{ CA_FILE }}"

listen:
  -
    port: {{ settings.XMPP_CLIENT_PORT }}
    ip: "::"
    module: ejabberd_c2s
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
    starttls: true

  -
    port: {{ settings.XMPP_SERVER_PORT }}
    ip: "::"
    module: ejabberd_s2s_in

{% if settings.XMPP_COMPONENT_MAX_ENABLED and settings.XMPP_COMPONENT_MAX_HOST and settings.XMPP_COMPONENT_MAX_PASSWORD %}
  -
    port: {{ settings.XMPP_COMPONENT_MAX_PORT }}
    ip: "{{ settings.XMPP_COMPONENT_MAX_IP }}"
    module: ejabberd_service
    hosts:
      "{{ settings.XMPP_COMPONENT_MAX_HOST }}":
        password: "{{ settings.XMPP_COMPONENT_MAX_PASSWORD }}"
{% endif %}

  - port: {{ settings.XMPP_HTTP_PORT }}
    ip: "::"
    module: ejabberd_http
    tls: true
    request_handlers:
      "/api": mod_http_api
      "/panel": mod_panel
      "/upload": mod_http_upload
      "/ws": ejabberd_http_ws
      "/iq": mod_http_iq
    custom_headers:
      "Access-Control-Allow-Methods": "GET,HEAD,PUT,OPTIONS"
      "Access-Control-Allow-Headers": "Content-Type"
      "Access-Control-Allow-Origin": "*"


  - port: {{ settings.XMPP_HTTPS_PORT }}
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/panel": mod_panel
      "/ws": ejabberd_http_ws
    custom_headers:
      "Access-Control-Allow-Methods": "GET,HEAD,PUT,OPTIONS"
      "Access-Control-Allow-Headers": "Content-Type"
      "Access-Control-Allow-Origin": "*"

s2s_use_starttls: optional

auth_password_format: scram
auth_method: sql

sql_type: pgsql
sql_server: "{{ db_host }}"
sql_database: "{{ db_name }}"
sql_username: "{{ db_user }}"
sql_password: {% if db_user_pass %}"{{ db_user_pass }}"{% endif %}
new_sql_schema: true

shaper:
  normal: 100000
  fast: 5000000

max_fsm_queue: 10000

acl:
  local:
    user_regexp: ""

  loopback:
    ip:
      - "127.0.0.0/8"
      - "::1/128"
      - "::FFFF:127.0.0.1/128"

shaper_rules:
  max_user_sessions: 20
  max_user_offline_messages:
    - 5000: admin
    - 100
  c2s_shaper:
    - none: admin
    - normal
  s2s_shaper: fast

access_rules:
  local:
    - allow: local
  c2s:
    - deny: blocked
    - allow
  announce:
    - allow: admin
  configure:
    - allow: admin
  muc_create:
    - allow: local
  pubsub_createnode:
    - allow: local
  register:
    - allow
  trusted_network:
    - allow: loopback

api_permissions:
  "console commands":
    from:
      - ejabberd_ctl
    who: all
    what: "*"
  "admin access":
    who:
      - access:
          - allow:
            - acl: loopback
            - acl: admin
      - oauth:
        - scope: "ejabberd:admin"
        - access:
          - allow:
            - acl: loopback
            - acl: admin
    what:
      - "*"
      - "!stop"
      - "!start"
  "public commands":
    who:
      - ip: "127.0.0.1/8"
    what:
      - "status"
      - "connected_users_number"

language: "en"

acme:
   contact: "mailto:example-admin@example.com"
   ca_url: "https://acme-v01.api.letsencrypt.org"

sm_db_type: mnesia
default_db: sql
default_ram_db: mnesia

allow_contrib_modules: true
include_config_file: "{{ VHOST_FILE }}"
include_config_file: "{{ MODULES_FILE }}"
include_config_file: "{{ ADD_CONFIG }}"
