modules:
  mod_adhoc: {}
  mod_admin_extra: {}
  mod_announce: # recommends mod_adhoc
    access: announce
  mod_blocking: {} # requires mod_privacy
  mod_caps: {}
  mod_carboncopy: {}
  mod_client_state: {}
  mod_configure: {} # requires mod_adhoc
  mod_disco: {}
  mod_echo: {}
  mod_http_upload:
    docroot: "{{ settings.USER_FILES }}"
    get_url: "https://xabber.@HOST@:{{ settings.XMPP_HTTPS_PORT }}/upload"
    put_url: "https://xabber.@HOST@:{{ settings.XMPP_HTTPS_PORT }}/upload"
  mod_last: {}
  mod_mam:
    default: always
    db_type: sql
    strip_outgoing_stanza_id: false
  mod_ping: {}
  mod_privacy: {}
  mod_private: {}
  mod_pubsub:
    db_type: sql
    access_createnode: pubsub_createnode
    ignore_pep_from_offline: false
    last_item_cache: false
    plugins:
      - "flat"
      - "hometree"
      - "pep"
    force_node_config:
      "eu.siacs.conversations.axolotl.*":
        access_model: whitelist
      "storage:bookmarks":
        access_model: whitelist
  mod_roster:
    versioning: true
  mod_shared_roster: {}
  mod_stats: {}
  mod_time: {}
  mod_vcard:
    search: false
  mod_vcard_xupdate: {}
  mod_avatar: {}
  mod_version: {}
  mod_stream_mgmt: {}
  mod_s2s_dialback: {}
  mod_http_api: {}
  mod_fail2ban: {}
  mod_unique: {}
  mod_retract: {}
  mod_sync: {}
  mod_devices: {}
  mod_permissions: { }
  mod_groups: {}
  mod_groups_permissions: { }
  mod_panel: {}
  mod_favorites: {}
  mod_notify: {}
  mod_nick_avatar:
    store_path: "{{ settings.MOD_NICK_AVATAR_FILES }}"
    amount: 20
  mod_block_users: {}
  mod_ws_proxy_detect: {}
  mod_xabber_push:
    db_type: sql
    use_cache: false
  mod_http_iq :
    url: "https://xabber.@HOST@:{{ settings.XMPP_HTTPS_PORT }}/iq"