# Generated by Django 3.2.25 on 2025-12-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XServicesToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('expires', models.DateTimeField()),
                ('jid', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
