# Generated by Django 3.2.25 on 2026-05-06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_module_refresh_token'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('options', models.TextField(blank=True, default='{}')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_configs', to='config.module')),
            ],
            options={
                'unique_together': {('module', 'name')},
            },
        ),
    ]
