# Generated by Django 3.2.25 on 2024-04-01 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_host', models.CharField(max_length=255, verbose_name='Related virtual host')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseXmppModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BaseXmppOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('verbose_name', models.TextField(blank=True, null=True)),
                ('version', models.CharField(max_length=20)),
                ('files', models.TextField(blank=True, null=True)),
                ('root_page', models.BooleanField(default=False)),
                ('global_module', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
                ('options', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RootPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(default='home', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('srv_records', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LDAPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypt', models.CharField(blank=True, choices=[('none', 'none'), ('tls', 'tls')], max_length=10, null=True)),
                ('tls_verify', models.CharField(blank=True, choices=[('false', 'false'), ('soft', 'soft'), ('hard', 'hard')], max_length=10, null=True)),
                ('tls_cacertfile', models.CharField(blank=True, max_length=100, null=True)),
                ('tls_depth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('port', models.PositiveSmallIntegerField(default=389)),
                ('rootdn', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('deref_aliases', models.CharField(blank=True, choices=[('never', 'never'), ('always', 'always'), ('finding', 'finding'), ('searching', 'searching')], max_length=100, null=True)),
                ('base', models.CharField(max_length=100)),
                ('uids', models.CharField(blank=True, max_length=256, null=True)),
                ('filter', models.CharField(blank=True, max_length=256, null=True)),
                ('dn_filter', models.CharField(blank=True, max_length=256, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ldap_settings', to='config.virtualhost')),
            ],
        ),
        migrations.CreateModel(
            name='LDAPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=50)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='config.ldapsettings')),
            ],
        ),
    ]
