# Generated by Django 3.2.25 on 2024-04-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('items', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='modulesettings',
            unique_together={('host', 'module')},
        ),
    ]
