# Generated by Django 3.2.25 on 2024-05-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_addsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualhost',
            name='cert_records',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualhost',
            name='issue_cert',
            field=models.BooleanField(default=False),
        ),
    ]
