# Generated by Django 3.2.25 on 2025-01-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20240507_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
