# Generated by Django 3.2.25 on 2025-01-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_module_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='track',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
