# Generated by Django 3.2.25 on 2025-02-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20250128_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
