# Generated by Django 2.2.9 on 2022-04-06 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('virtualhost', '0016_user_auth_backend'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_enabled_by_key', models.BooleanField(default=False)),
                ('vhost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualhost.VirtualHost')),
            ],
        ),
    ]
