# Generated by Django 3.2.25 on 2024-04-03 12:19

from django.db import migrations, models
from ..models import CronJob


def create_base_cron_jobs(*args, **kwargs):

    CronJob.objects.create(
        schedule="0 * * * *",
        command="check_expires",
        active=False,
        type='built_in_job'
    )
    CronJob.objects.create(
        schedule="0 13 * * *",
        command="update_certs",
        active=False,
        type='built_in_job'
    )


def delete_base_cron_jobs(apps, schema_editor):
    CronJob.objects.filter(
        command__in=['check_expires', 'update_certs'],
        type='built_in_job'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crontab', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_base_cron_jobs, reverse_code=delete_base_cron_jobs),
    ]
