# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualhost', '0004_auto_20190522_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='identifier',
            new_name='group',
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('group', 'host')]),
        ),
    ]
