# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualhost', '0006_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('host', models.CharField(max_length=256)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtualhost.Group')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=set([('username', 'host')]),
        ),
    ]
