# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualhost', '0007_auto_20190619_0939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=set([('group', 'username', 'host')]),
        ),
    ]
