# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-06 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualhost', '0010_auto_20190709_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='prefix',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
