# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-27 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualhost', '0013_auto_20191122_0657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthBackend',
        ),
    ]
