# Generated by Django 2.2.9 on 2020-06-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualhost', '0015_auto_20200117_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_backend',
            field=models.CharField(choices=[('sql', 'internal'), ('ldap', 'LDAP')], default='sql', max_length=128),
        ),
    ]
