# Generated by Django 2.2.9 on 2021-02-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualhost', '0017_auto_20201109_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
