# Generated by Django 2.2.9 on 2022-11-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualhost', '0018_auto_20220415_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('BANNED', 'BANNED'), ('EXPIRED', 'EXPIRED'), ('SUSPENDED', 'SUSPENDED')], default='ACTIVE', max_length=50),
        ),
    ]
