# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_host', models.CharField(max_length=256)),
                ('db_name', models.CharField(max_length=256)),
                ('db_user', models.CharField(max_length=256)),
                ('db_user_pass', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
