# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-27 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthBackend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'sql', b'SQL'), (b'ldap', b'LDAP')], max_length=10)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
