# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-27 09:42
from __future__ import unicode_literals

from django.db import migrations


BACKEND_SQL = 'sql'
BACKEND_LDAP = 'ldap'


def add_auth_backends(apps, schema_editor):
    AuthBackend = apps.get_model('server', 'AuthBackend')
    AuthBackend.objects.create(name=BACKEND_SQL, is_active=True)
    AuthBackend.objects.create(name=BACKEND_LDAP, is_active=False)


def remove_auth_backends(apps, schema_editor):
    AuthBackend = apps.get_model('server', 'AuthBackend')
    AuthBackend.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_authbackend'),
    ]

    operations = [
        migrations.RunPython(add_auth_backends, remove_auth_backends)
    ]
