# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-27 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20191127_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapsettings',
            name='base',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ldapsettings',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ldapsettings',
            name='rootdn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
