# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-08 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20191127_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_base', models.CharField(max_length=100)),
                ('ldap_filter', models.CharField(blank=True, max_length=100, null=True)),
                ('ldap_dn_filter', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LDAPAuthUid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_uidattr', models.CharField(max_length=100)),
                ('ldap_uidattr_format', models.CharField(blank=True, max_length=100, null=True)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.LDAPAuth')),
            ],
        ),
        migrations.RenameModel(
            old_name='LDAPServer',
            new_name='LDAPSettingsServer',
        ),
        migrations.RenameField(
            model_name='ldapsettings',
            old_name='password',
            new_name='ldap_password',
        ),
        migrations.RenameField(
            model_name='ldapsettings',
            old_name='rootdn',
            new_name='ldap_rootdn',
        ),
        migrations.RemoveField(
            model_name='ldapsettings',
            name='base',
        ),
        migrations.RemoveField(
            model_name='ldapsettings',
            name='port',
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='ldap_deref_aliases',
            field=models.CharField(blank=True, choices=[(b'never', b'never'), (b'always', b'always'), (b'finding', b'finding'), (b'searching', b'searching')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='ldap_encrypt',
            field=models.CharField(blank=True, choices=[(b'none', b'none'), (b'tls', b'tls')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='ldap_port',
            field=models.PositiveSmallIntegerField(default=389),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='ldap_tls_cacertfile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='ldap_tls_depth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='ldap_tls_verify',
            field=models.CharField(blank=True, choices=[(b'false', b'false'), (b'soft', b'soft'), (b'hard', b'hard')], max_length=100, null=True),
        ),
    ]
