# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-09 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20191208_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapauthuid',
            name='auth',
        ),
        migrations.AddField(
            model_name='ldapauth',
            name='ldap_uids',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ldapauth',
            name='ldap_dn_filter',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ldapauth',
            name='ldap_filter',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='LDAPAuthUid',
        ),
    ]
