# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-11 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20191209_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapsettings',
            name='ldap_deref_aliases',
            field=models.CharField(blank=True, choices=[(None, b'--'), (b'never', b'never'), (b'always', b'always'), (b'finding', b'finding'), (b'searching', b'searching')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ldapsettings',
            name='ldap_encrypt',
            field=models.CharField(blank=True, choices=[(None, b'--'), (b'none', b'none'), (b'tls', b'tls')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ldapsettings',
            name='ldap_tls_verify',
            field=models.CharField(blank=True, choices=[(None, b'--'), (b'false', b'false'), (b'soft', b'soft'), (b'hard', b'hard')], max_length=100, null=True),
        ),
    ]
