# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-19 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualhost', '0014_delete_authbackend'),
        ('server', '0009_auto_20191211_1036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LDAPAuth',
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='ldap_base',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='ldap_dn_filter',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='ldap_filter',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='ldap_uids',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='ldap_vhost',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='virtualhost.VirtualHost'),
            preserve_default=False,
        ),
    ]
