# Generated by Django 2.2.9 on 2020-01-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20191219_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authbackend',
            name='name',
            field=models.CharField(choices=[('sql', 'SQL'), ('ldap', 'LDAP')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ldapsettings',
            name='ldap_deref_aliases',
            field=models.CharField(blank=True, choices=[(None, '--'), ('never', 'never'), ('always', 'always'), ('finding', 'finding'), ('searching', 'searching')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ldapsettings',
            name='ldap_encrypt',
            field=models.CharField(blank=True, choices=[(None, '--'), ('none', 'none'), ('tls', 'tls')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ldapsettings',
            name='ldap_tls_verify',
            field=models.CharField(blank=True, choices=[(None, '--'), ('false', 'false'), ('soft', 'soft'), ('hard', 'hard')], max_length=100, null=True),
        ),
    ]
