# Generated by Django 3.2.12 on 2022-04-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_configuration_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootPageSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(default='home_page', max_length=50)),
            ],
        ),
    ]
